{% set name = "appmap" %}
{% set version = "1.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/appmap-{{ version }}.tar.gz
  sha256: 8f63d96bd5c34120f8c1398929762e7a883a3998387d6e5c6d5dab37643d6e60

build:
  number: 0
  noarch: python
  entry_points:
    - appmap-agent-init = appmap.command.appmap_agent_init:run
    - appmap-agent-status = appmap.command.appmap_agent_status:run
    - appmap-agent-validate = appmap.command.appmap_agent_validate:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry-core >=1,<2
    - pip
    - python >=3.6,<4.0
  run:
    - importlib-metadata >=0.8
    - inflection >=0.3.0
    - python >=3.6,<4.0
    - pyyaml >=5.3.0,<6.0.0

test:
  imports:
    - appmap
    - appmap._implementation
  commands:
    - pip check
    - appmap-agent-init --help
    - appmap-agent-status --help
    - appmap-agent-validate --help
  requires:
    - pip

about:
  home: https://github.com/applandinc/appmap-python
  summary: Create AppMap files by recording a Python application.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
