{% set name = "appmap" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/appmap-{{ version }}.tar.gz
  sha256: 262646c019fbe8c7b6d6a7bd443bb9efdb46dc162e42019837b41c6e527245c3

build:
  number: 0
  noarch: python
  entry_points:
    - appmap-agent-init = appmap.command.appmap_agent_init:run
    - appmap-agent-status = appmap.command.appmap_agent_status:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry
    - pip
    - python >=3.6,<4.0
  run:
    - importlib-metadata >=0.8
    - inflection >=0.3.0,<0.4.0
    - python >=3.6,<4.0
    - pyyaml >=5.3.0,<6.0.0

test:
  imports:
    - appmap
    - appmap._implementation
  commands:
    - pip check
    - appmap-agent-init --help
    - appmap-agent-status --help
  requires:
    - pip

about:
  home: https://github.com/applandinc/appmap-python
  summary: Create AppMap files by recording a Python application.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
