{% set name = "appmap" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/appmap-{{ version }}.tar.gz
  sha256: fa091f0529ee3d57bd394daa70f3b21632c81f613508d7317717e03d6e78763a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry
    - pip
    - python >=3.6,<4.0
  run:
    - importlib-metadata >=0.8
    - inflection >=0.3.0,<0.4.0
    - python >=3.6,<4.0
    - pyyaml >=5.3.0,<5.4.0
    - twisted >=21.2.0,<22.0.0

test:
  imports:
    - appmap
    - appmap._implementation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/applandinc/appmap-python
  summary: Create AppMap files by recording a Python application.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
